version: '3.8'

services: 
  redis: 
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "123456"]
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes: 
  redis_data: 